### ISSUE TITLE
Tokens YAML fails to match

### ISSUE THREAD

**Issue by wcravens** [cantino/reckon#73]
albus:~ wcravens$ reckon --version
    Reckon 0.4.4

I have the following test csv file

    Transaction Date,Description,Amount,Category
    07/06/2017,TRIPLE T CAR WASH CHAMPAIGN IL,$27.00,Automotive

I'm trying to parse it with the following command

    reckon --unattended --account-tokens tokens_good.yaml \
    --account "Liabilities:Credit Cards:Visa" \
    -f testy.csv --contains-header --ignore-column 4 \
    -i --date-format '%m/%d/%Y' -o output.dat

Using the following tokens_bad.yaml with implicit string doesn't work

    Expenses:
      Automotive:
        Car Wash:
          - 'TRIPLE T CAR WASH CHAMPAIGN IL'

Results:

    2017/07/06  TRIPLE T CAR WASH CHAMPAIGN IL
      Expenses:Unknown          $27.00
      Liabilities:Credit Cards:UIECU Visa         -$27.00

Using the following tokens_good.yaml with regex does work

    Expenses:
      Automotive:
        Car Wash:
          - /TRIPLE T CAR WASH CHAMPAIGN IL/

Results:

    2017/07/06  TRIPLE T CAR WASH CHAMPAIGN IL
      Expenses:Automotive:Car Wash          $27.00
      Liabilities:Credit Cards:UIECU Visa         -$27.00

Is this expected behavior or a bug?  If a bug I will try and track down why.  I did read about issue #52 which lead me to  `--ignore-column 4`.

**Comment by benprew** [comment]
Hi @wcravens, thanks for using Reckon. I'm the new maintainer, and I know it's been a while since you posted this issue, but wanted to follow up, in case it was still important to you.

Looking at app.rb, when you use a regex, it will do a regex match, otherwise it tokenizes the string and uses them as weights.

I agree with your assessment that this is a bug.  I'll add a test case and work on a fix.  Thanks for reporting this.
