### ISSUE TITLE
Learn-from not working

### ISSUE THREAD

**Issue by kototama** [cantino/reckon#74]
Hi,

I am specifying a file to learn from with `-l` but nothing get classified even if transactions are similar.

How can I troubleshoot?

**Comment by benprew** [comment]
Hi @kototama , thanks for using Reckon.  I'm the new maintainer, and I know it's been a while since you posted this issue, but wanted to follow up, in case it was still important to you.

Unfortunately, there's no way to to specify a command line option to do it, but if you want to dig into the repo, in app.rb, the walk_backwards function sets a possible_answers variable that you could inspect to see what reckon thinks the possible answers are.

Does that path work for you?

**Comment by benprew** [comment]
This should be fixed in #79 .  If not, please let me know.

**Comment by kototama** [comment]
Thanks for coming back to this issue. Sorry for the late reply. I don't use the software at the moment but it helped me a lot at the time. I will contact you via github issues in the future if I reuse in the future and encounter problems.
